spring:
  application:
    name: LPrutas
  datasource:
    plataform: MySQL
    url: jdbc:mysql://localhost:3306/lpbus_bot
    username: fer
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true