spring:
  application:
    name: LPrutas
  datasource:
    plataform: MySQL
    url: jdbc:mysql://localhost:3306/dbtest_lpbus2
    username: fer
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        legacy_limit_handler: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true